// Code generated by gsus-db2struct. DO NOT EDIT.
//
//go:generate gsus db2struct orders
package mogo

import (
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// orders :
type Orders struct {
	ID          primitive.ObjectID `gorm:"column:_id;primaryKey;type:objectId" bson:"_id" json:"_id"`
	TotalAmount float64            `gorm:"column:total_amount;type:double" bson:"total_amount,omitempty" json:"total_amount"`
	Status      string             `gorm:"column:status;type:string" bson:"status,omitempty" json:"status"`
	Items       bson.A             `gorm:"column:items;type:array" bson:"items,omitempty" json:"items"`
	CreatedAt   time.Time          `gorm:"column:created_at;autoCreateTime;type:timestamp" bson:"created_at,omitempty" json:"created_at"`
	UserID      int32              `gorm:"column:user_id;type:int32" bson:"user_id,omitempty" json:"user_id"`
	OrderNo     string             `gorm:"column:order_no;type:string;uniqueIndex:order_no_1" bson:"order_no,omitempty" json:"order_no"`
}

const TableOrders = "orders"

func (o *Orders) TableName() string {
	return TableOrders
}

type OrdersSlice []Orders

func (this OrdersSlice) ForEach(f func(index int, t *Orders)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this OrdersSlice) Filter(f func(t *Orders) bool) OrdersSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(OrdersSlice, 0, len(this))
	this.ForEach(func(_ int, t *Orders) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type OrdersIntMap map[int]*Orders

func (this OrdersIntMap) ForEach(f func(key int, t *Orders)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this OrdersSlice) MapInt(mapFunc func(*Orders) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Orders) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this OrdersSlice) GroupInt(mapFunc func(*Orders) int) (ret map[int]OrdersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]OrdersSlice)
	this.ForEach(func(_ int, t *Orders) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this OrdersSlice) ToIntMap(indexBy func(t *Orders) int) (m OrdersIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(OrdersIntMap)
	this.ForEach(func(_ int, t *Orders) {
		m[indexBy(t)] = t
	})
	return m
}

type OrdersStringMap map[string]*Orders

func (this OrdersStringMap) ForEach(f func(key string, t *Orders)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this OrdersSlice) MapString(mapFunc func(*Orders) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Orders) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this OrdersSlice) GroupString(mapFunc func(*Orders) string) (ret map[string]OrdersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]OrdersSlice)
	this.ForEach(func(_ int, t *Orders) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this OrdersSlice) ToStringMap(indexBy func(t *Orders) string) (m OrdersStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(OrdersStringMap)
	this.ForEach(func(_ int, t *Orders) {
		m[indexBy(t)] = t
	})
	return m
}
