// Code generated by gsus-db2struct. DO NOT EDIT.
//
//go:generate gsus db2struct products
package mogo

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// products :
type Products struct {
	ID          primitive.ObjectID `gorm:"column:_id;primaryKey;type:objectId" bson:"_id" json:"_id"`
	Price       float64            `gorm:"column:price;type:double" bson:"price,omitempty" json:"price"`
	Stock       int32              `gorm:"column:stock;type:int32" bson:"stock,omitempty" json:"stock"`
	Category    string             `gorm:"column:category;type:string;index:category_1" bson:"category,omitempty" json:"category"`
	Status      string             `gorm:"column:status;type:string" bson:"status,omitempty" json:"status"`
	CreatedAt   time.Time          `gorm:"column:created_at;autoCreateTime;type:timestamp" bson:"created_at,omitempty" json:"created_at"`
	Name        string             `gorm:"column:name;type:string;index:name_1" bson:"name,omitempty" json:"name"`
	Description string             `gorm:"column:description;type:string" bson:"description,omitempty" json:"description"`
}

const TableProducts = "products"

func (p *Products) TableName() string {
	return TableProducts
}

type ProductsSlice []Products

func (this ProductsSlice) ForEach(f func(index int, t *Products)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this ProductsSlice) Filter(f func(t *Products) bool) ProductsSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(ProductsSlice, 0, len(this))
	this.ForEach(func(_ int, t *Products) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type ProductsIntMap map[int]*Products

func (this ProductsIntMap) ForEach(f func(key int, t *Products)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this ProductsSlice) MapInt(mapFunc func(*Products) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Products) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this ProductsSlice) GroupInt(mapFunc func(*Products) int) (ret map[int]ProductsSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]ProductsSlice)
	this.ForEach(func(_ int, t *Products) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this ProductsSlice) ToIntMap(indexBy func(t *Products) int) (m ProductsIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(ProductsIntMap)
	this.ForEach(func(_ int, t *Products) {
		m[indexBy(t)] = t
	})
	return m
}

type ProductsStringMap map[string]*Products

func (this ProductsStringMap) ForEach(f func(key string, t *Products)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this ProductsSlice) MapString(mapFunc func(*Products) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Products) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this ProductsSlice) GroupString(mapFunc func(*Products) string) (ret map[string]ProductsSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]ProductsSlice)
	this.ForEach(func(_ int, t *Products) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this ProductsSlice) ToStringMap(indexBy func(t *Products) string) (m ProductsStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(ProductsStringMap)
	this.ForEach(func(_ int, t *Products) {
		m[indexBy(t)] = t
	})
	return m
}
