// Code generated by gsus-db2struct. DO NOT EDIT.
//
//go:generate gsus db2struct users
package mogo

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// users :
type Users struct {
	ID        primitive.ObjectID `gorm:"column:_id;primaryKey;type:objectId" bson:"_id" json:"_id"`
	Balance   float64            `gorm:"column:balance;type:double" bson:"balance,omitempty" json:"balance"`
	CreatedAt time.Time          `gorm:"column:created_at;autoCreateTime;type:timestamp" bson:"created_at,omitempty" json:"created_at"`
	Username  string             `gorm:"column:username;type:string;index:username_1" bson:"username,omitempty" json:"username"`
	Email     string             `gorm:"column:email;type:string;uniqueIndex:email_1" bson:"email,omitempty" json:"email"`
	UpdatedAt time.Time          `gorm:"column:updated_at;autoUpdateTime;type:timestamp" bson:"updated_at,omitempty" json:"updated_at"`
	IsActive  bool               `gorm:"column:is_active;type:bool" bson:"is_active,omitempty" json:"is_active"`
	Age       int32              `gorm:"column:age;type:int32" bson:"age,omitempty" json:"age"`
	Password  string             `gorm:"column:password;type:string" bson:"password,omitempty" json:"password"`
}

const TableUsers = "users"

func (u *Users) TableName() string {
	return TableUsers
}

type UsersSlice []Users

func (this UsersSlice) ForEach(f func(index int, t *Users)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this UsersSlice) Filter(f func(t *Users) bool) UsersSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(UsersSlice, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type UsersIntMap map[int]*Users

func (this UsersIntMap) ForEach(f func(key int, t *Users)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this UsersSlice) MapInt(mapFunc func(*Users) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this UsersSlice) GroupInt(mapFunc func(*Users) int) (ret map[int]UsersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]UsersSlice)
	this.ForEach(func(_ int, t *Users) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this UsersSlice) ToIntMap(indexBy func(t *Users) int) (m UsersIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(UsersIntMap)
	this.ForEach(func(_ int, t *Users) {
		m[indexBy(t)] = t
	})
	return m
}

type UsersStringMap map[string]*Users

func (this UsersStringMap) ForEach(f func(key string, t *Users)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this UsersSlice) MapString(mapFunc func(*Users) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this UsersSlice) GroupString(mapFunc func(*Users) string) (ret map[string]UsersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]UsersSlice)
	this.ForEach(func(_ int, t *Users) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this UsersSlice) ToStringMap(indexBy func(t *Users) string) (m UsersStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(UsersStringMap)
	this.ForEach(func(_ int, t *Users) {
		m[indexBy(t)] = t
	})
	return m
}
