// Code generated by gsus-db2struct. DO NOT EDIT.
// 用户表
//
//go:generate gsus db2struct users
package postgres

import "database/sql"

// users : 用户表
type Users struct {
	ID        int64           `gorm:"column:id;primary_key;autoIncrement;type:bigint;not null" sql:"default:nextval('users_id_seq'::regclass)"` // 用户ID
	Username  string          `gorm:"column:username;type:character varying;not null;index:idx_username"`                                       // 用户名
	Email     sql.NullString  `gorm:"column:email;type:character varying;index:idx_email;unique_index:users_email_key"`                         // 邮箱
	Password  string          `gorm:"column:password;type:character varying;not null"`
	Age       sql.NullInt64   `gorm:"column:age;type:integer"`
	Balance   sql.NullFloat64 `gorm:"column:balance;type:numeric" sql:"default:0.00"`
	IsActive  sql.NullBool    `gorm:"column:is_active;type:boolean" sql:"default:true"`
	CreatedAt sql.NullTime    `gorm:"column:created_at;type:timestamp without time zone" sql:"default:CURRENT_TIMESTAMP"`
	UpdatedAt sql.NullTime    `gorm:"column:updated_at;type:timestamp without time zone" sql:"default:CURRENT_TIMESTAMP"`
}

const TableUsers = "users"

func (u *Users) TableName() string {
	return TableUsers
}

type UsersSlice []Users

func (this UsersSlice) ForEach(f func(index int, t *Users)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this UsersSlice) Filter(f func(t *Users) bool) UsersSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(UsersSlice, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type UsersIntMap map[int]*Users

func (this UsersIntMap) ForEach(f func(key int, t *Users)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this UsersSlice) MapInt(mapFunc func(*Users) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this UsersSlice) GroupInt(mapFunc func(*Users) int) (ret map[int]UsersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]UsersSlice)
	this.ForEach(func(_ int, t *Users) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this UsersSlice) ToIntMap(indexBy func(t *Users) int) (m UsersIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(UsersIntMap)
	this.ForEach(func(_ int, t *Users) {
		m[indexBy(t)] = t
	})
	return m
}

type UsersStringMap map[string]*Users

func (this UsersStringMap) ForEach(f func(key string, t *Users)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this UsersSlice) MapString(mapFunc func(*Users) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this UsersSlice) GroupString(mapFunc func(*Users) string) (ret map[string]UsersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]UsersSlice)
	this.ForEach(func(_ int, t *Users) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this UsersSlice) ToStringMap(indexBy func(t *Users) string) (m UsersStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(UsersStringMap)
	this.ForEach(func(_ int, t *Users) {
		m[indexBy(t)] = t
	})
	return m
}
