package db2struct

import (
	"fmt"

	"github.com/spelens-gud/gsus/apis/helpers"
)

// Constants for return types of golang
const (
	golangByteArray = "[]byte"
	golangInt       = "int"
	golangInt64     = "int64"
	golangFloat32   = "float32"
	golangFloat64   = "float64"
	golangTime      = "time.Time"
	golangInterface = "interface{}"

	sqlNullInt    = "sql.NullInt64"
	sqlNullFloat  = "sql.NullFloat64"
	sqlNullString = "sql.NullString"
	sqlNullTime   = "sql.NullTime"
)

// commonInitialisms is a set of common initialisms.
// Only add entries that are highly unlikely to be non-initialisms.
// For instance, "ID" is fine (Freudian code is rare), but "AND" is not.
var commonInitialisms = map[string]bool{
	"API":   true,
	"ASCII": true,
	"CPU":   true,
	"CSS":   true,
	"DNS":   true,
	"EOF":   true,
	"GUID":  true,
	"HTML":  true,
	"HTTP":  true,
	"HTTPS": true,
	"ID":    true,
	"IP":    true,
	"JSON":  true,
	"LHS":   true,
	"QPS":   true,
	"RAM":   true,
	"RHS":   true,
	"RPC":   true,
	"SLA":   true,
	"SMTP":  true,
	"SSH":   true,
	"TLS":   true,
	"TTL":   true,
	"UI":    true,
	"UID":   true,
	"UUID":  true,
	"URI":   true,
	"URL":   true,
	"UTF8":  true,
	"VM":    true,
	"XML":   true,
}

var intToWordMap = []string{
	"zero",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
}

type cTypes struct {
	Key  string
	Info map[string]string
}

const headTemplate = `// Code generated by gsus-db2struct. DO NOT EDIT.
// %s
//go:generate gsus db2struct %s
package %s

// %s %s
type %s %s`

const tableFuncTemplate = `const Table%s = "%s"
func (%s *%s) TableName() string {
	return Table%s
}`

// Generate Given a Column map with datatypes and a name structName,
// attempts to generate a struct definition
func Generate(columnTypes []cTypes, tableName, structName, pkgName, tableComment string, opts *opt) ([]byte, map[string]string) {
	dbTypes, fieldNameMap := generateMysqlTypes(columnTypes, 0, opts)
	src := fmt.Sprintf(headTemplate, tableComment, tableName, pkgName, tableName, ": "+tableComment, structName, dbTypes)
	tableNameFunc := fmt.Sprintf(tableFuncTemplate, structName, tableName, helpers.GetFuncCallerIdent(structName), structName, structName)
	return []byte(src + "\n\n" + tableNameFunc), fieldNameMap
}
