// Code generated by gsus-db2struct. DO NOT EDIT.
//
//go:generate gsus db2struct alibaba_1688_account
package table

import "time"

// alibaba_1688_account :
type alibaba_1688_account struct {
	ID              int64     `gorm:"column:id;primary_key;auto_increment;TYPE:bigint unsigned;NOT NULL"`
	AccountName     string    `gorm:"column:account_name;TYPE:varchar(100);NOT NULL"`  // 账号名称
	MemberID        string    `gorm:"column:member_id;TYPE:varchar(100);NOT NULL"`     // 会员ID
	AppKey          string    `gorm:"column:app_key;TYPE:varchar(100);NOT NULL"`       // 应用Key
	AppSecret       string    `gorm:"column:app_secret;TYPE:varchar(200);NOT NULL"`    // 应用密钥
	AccessToken     string    `gorm:"column:access_token;TYPE:varchar(500);NOT NULL"`  // 访问令牌
	RefreshToken    string    `gorm:"column:refresh_token;TYPE:varchar(500);NOT NULL"` // 刷新令牌
	TokenExpireTime time.Time `gorm:"column:token_expire_time;TYPE:datetime;NOT NULL"` // 令牌过期时间
	Purchaser       string    `gorm:"column:purchaser;TYPE:varchar(500);NOT NULL"`     // 导购员
	PurchaseGroup   string    `gorm:"column:purchaseGroup;TYPE:varchar(500);NOT NULL"` // 导购组
	Status          int       `gorm:"column:status;TYPE:tinyint;NOT NULL"`             // 状态 1:启用 0:禁用
	Remark          string    `gorm:"column:remark;TYPE:varchar(500);NOT NULL"`        // 备注
	CreatedAt       time.Time `gorm:"column:created_at;TYPE:datetime;NOT NULL"`
	UpdatedAt       time.Time `gorm:"column:updated_at;TYPE:datetime;NOT NULL"`
}

const Tablealibaba_1688_account = "alibaba_1688_account"

func (a *alibaba_1688_account) TableName() string {
	return Tablealibaba_1688_account
}

type alibaba_1688_accountSlice []alibaba_1688_account

func (this alibaba_1688_accountSlice) ForEach(f func(index int, t *alibaba_1688_account)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this alibaba_1688_accountSlice) Filter(f func(t *alibaba_1688_account) bool) alibaba_1688_accountSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(alibaba_1688_accountSlice, 0, len(this))
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type alibaba_1688_accountIntMap map[int]*alibaba_1688_account

func (this alibaba_1688_accountIntMap) ForEach(f func(key int, t *alibaba_1688_account)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this alibaba_1688_accountSlice) MapInt(mapFunc func(*alibaba_1688_account) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this alibaba_1688_accountSlice) GroupInt(mapFunc func(*alibaba_1688_account) int) (ret map[int]alibaba_1688_accountSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]alibaba_1688_accountSlice)
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this alibaba_1688_accountSlice) ToIntMap(indexBy func(t *alibaba_1688_account) int) (m alibaba_1688_accountIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(alibaba_1688_accountIntMap)
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		m[indexBy(t)] = t
	})
	return m
}

type alibaba_1688_accountStringMap map[string]*alibaba_1688_account

func (this alibaba_1688_accountStringMap) ForEach(f func(key string, t *alibaba_1688_account)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this alibaba_1688_accountSlice) MapString(mapFunc func(*alibaba_1688_account) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this alibaba_1688_accountSlice) GroupString(mapFunc func(*alibaba_1688_account) string) (ret map[string]alibaba_1688_accountSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]alibaba_1688_accountSlice)
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this alibaba_1688_accountSlice) ToStringMap(indexBy func(t *alibaba_1688_account) string) (m alibaba_1688_accountStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(alibaba_1688_accountStringMap)
	this.ForEach(func(_ int, t *alibaba_1688_account) {
		m[indexBy(t)] = t
	})
	return m
}
