// Code generated by gsus-db2struct. DO NOT EDIT.
// 采购订单详情表
//
//go:generate gsus db2struct purchase_orders
package table

import "time"

// purchase_orders : 采购订单详情表
type purchase_orders struct {
	ID                  int64     `gorm:"column:id;primary_key;auto_increment;TYPE:bigint;NOT NULL"`                             // 主键ID
	PurchaseOrderNo     string    `gorm:"column:purchase_order_no;TYPE:varchar(255);NOT NULL;UNIQUE_INDEX:uk_purchase_order_no"` // 采购单号
	OrderSource         string    `gorm:"column:order_source;TYPE:varchar(255);NOT NULL"`                                        // 订单来源
	OrderStatus         string    `gorm:"column:order_status;TYPE:varchar(255);NOT NULL"`                                        // 订单状态
	Supplier            string    `gorm:"column:supplier;TYPE:varchar(255);NOT NULL"`                                            // 供应商
	Account1688         string    `gorm:"column:account_1688;TYPE:varchar(255);NOT NULL"`                                        // 1688账号
	OrderNo1688         string    `gorm:"column:order_no_1688;TYPE:varchar(255);NOT NULL"`                                       // 1688单号
	Purchaser           string    `gorm:"column:purchaser;TYPE:varchar(255);NOT NULL"`                                           // 采购员
	PurchaseGroup       string    `gorm:"column:purchase_group;TYPE:varchar(255);NOT NULL"`                                      // 采购组
	OrderTime           string    `gorm:"column:order_time;TYPE:varchar(255);NOT NULL"`                                          // 下单时间
	PayTime             string    `gorm:"column:pay_time;TYPE:varchar(255);NOT NULL"`                                            // 付款时间
	PromiseDeliveryTime string    `gorm:"column:promise_delivery_time;TYPE:varchar(255);NOT NULL"`                               // 预计交期
	TimeoutTime         string    `gorm:"column:timeout_time;TYPE:varchar(255);NOT NULL"`                                        // 超时时间
	ReceiverPhone       string    `gorm:"column:receiver_phone;TYPE:varchar(255);NOT NULL"`                                      // 收货手机号
	ReceiverAddress     string    `gorm:"column:receiver_address;TYPE:varchar(255);NOT NULL"`                                    // 收获地址
	GoodsTotal          int64     `gorm:"column:goods_total;TYPE:bigint;NOT NULL"`                                               // 商品总数
	InStock             int64     `gorm:"column:in_stock;TYPE:bigint;NOT NULL"`                                                  // 入库数量
	NotInStock          int64     `gorm:"column:not_in_stock;TYPE:bigint;NOT NULL"`                                              // 未入库数量
	LogisticsInfos      string    `gorm:"column:logistics_infos;TYPE:text;NOT NULL"`                                             // 物流轨迹列表
	CreatedAt           time.Time `gorm:"column:created_at;TYPE:datetime;NOT NULL"`                                              // 创建时间
	UpdatedAt           time.Time `gorm:"column:updated_at;TYPE:datetime;NOT NULL"`                                              // 更新时间
}

const Tablepurchase_orders = "purchase_orders"

func (p *purchase_orders) TableName() string {
	return Tablepurchase_orders
}

type purchase_ordersSlice []purchase_orders

func (this purchase_ordersSlice) ForEach(f func(index int, t *purchase_orders)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this purchase_ordersSlice) Filter(f func(t *purchase_orders) bool) purchase_ordersSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(purchase_ordersSlice, 0, len(this))
	this.ForEach(func(_ int, t *purchase_orders) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type purchase_ordersIntMap map[int]*purchase_orders

func (this purchase_ordersIntMap) ForEach(f func(key int, t *purchase_orders)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this purchase_ordersSlice) MapInt(mapFunc func(*purchase_orders) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *purchase_orders) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this purchase_ordersSlice) GroupInt(mapFunc func(*purchase_orders) int) (ret map[int]purchase_ordersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]purchase_ordersSlice)
	this.ForEach(func(_ int, t *purchase_orders) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this purchase_ordersSlice) ToIntMap(indexBy func(t *purchase_orders) int) (m purchase_ordersIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(purchase_ordersIntMap)
	this.ForEach(func(_ int, t *purchase_orders) {
		m[indexBy(t)] = t
	})
	return m
}

type purchase_ordersStringMap map[string]*purchase_orders

func (this purchase_ordersStringMap) ForEach(f func(key string, t *purchase_orders)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this purchase_ordersSlice) MapString(mapFunc func(*purchase_orders) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *purchase_orders) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this purchase_ordersSlice) GroupString(mapFunc func(*purchase_orders) string) (ret map[string]purchase_ordersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]purchase_ordersSlice)
	this.ForEach(func(_ int, t *purchase_orders) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this purchase_ordersSlice) ToStringMap(indexBy func(t *purchase_orders) string) (m purchase_ordersStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(purchase_ordersStringMap)
	this.ForEach(func(_ int, t *purchase_orders) {
		m[indexBy(t)] = t
	})
	return m
}
