// Code generated by gsus-db2struct. DO NOT EDIT.
// 催发记录表
//
//go:generate gsus db2struct urge_record
package table

import "time"

// urge_record : 催发记录表
type urge_record struct {
	ID              int64     `gorm:"column:id;primary_key;auto_increment;TYPE:bigint;NOT NULL"`                       // 主键ID
	WhitelistID     int64     `gorm:"column:whitelist_id;TYPE:bigint;NOT NULL;INDEX:idx_whitelist_id"`                 // 白名单ID
	SupplierCode    string    `gorm:"column:supplier_code;TYPE:varchar(100);NOT NULL;INDEX:idx_supplier_code"`         // 供应商编码
	PurchaseOrderNo string    `gorm:"column:purchase_order_no;TYPE:varchar(100);NOT NULL;INDEX:idx_purchase_order_no"` // 采购单号
	UrgeType        string    `gorm:"column:urge_type;TYPE:varchar(50);NOT NULL"`                                      // 催发类型: auto-自动, manual-手动
	UrgeMethod      string    `gorm:"column:urge_method;TYPE:varchar(50);NOT NULL"`                                    // 催发方式: system-系统(后续可能会扩展)
	UrgeContent     string    `gorm:"column:urge_content;TYPE:text;NOT NULL"`                                          // 催发内容
	UrgeResult      string    `gorm:"column:urge_result;TYPE:varchar(50);NOT NULL"`                                    // 催发结果: success-成功, failed-失败
	UrgeTime        time.Time `gorm:"column:urge_time;TYPE:datetime;NOT NULL;INDEX:idx_urge_time"`                     // 催发时间
	Operator        string    `gorm:"column:operator;TYPE:varchar(100);NOT NULL"`                                      // 操作人
	Remark          string    `gorm:"column:remark;TYPE:varchar(500);NOT NULL"`                                        // 备注
	CreatedAt       time.Time `gorm:"column:created_at;TYPE:datetime;NOT NULL"`                                        // 创建时间
}

const Tableurge_record = "urge_record"

func (u *urge_record) TableName() string {
	return Tableurge_record
}

type urge_recordSlice []urge_record

func (this urge_recordSlice) ForEach(f func(index int, t *urge_record)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this urge_recordSlice) Filter(f func(t *urge_record) bool) urge_recordSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(urge_recordSlice, 0, len(this))
	this.ForEach(func(_ int, t *urge_record) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type urge_recordIntMap map[int]*urge_record

func (this urge_recordIntMap) ForEach(f func(key int, t *urge_record)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this urge_recordSlice) MapInt(mapFunc func(*urge_record) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *urge_record) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this urge_recordSlice) GroupInt(mapFunc func(*urge_record) int) (ret map[int]urge_recordSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]urge_recordSlice)
	this.ForEach(func(_ int, t *urge_record) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this urge_recordSlice) ToIntMap(indexBy func(t *urge_record) int) (m urge_recordIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(urge_recordIntMap)
	this.ForEach(func(_ int, t *urge_record) {
		m[indexBy(t)] = t
	})
	return m
}

type urge_recordStringMap map[string]*urge_record

func (this urge_recordStringMap) ForEach(f func(key string, t *urge_record)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this urge_recordSlice) MapString(mapFunc func(*urge_record) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *urge_record) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this urge_recordSlice) GroupString(mapFunc func(*urge_record) string) (ret map[string]urge_recordSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]urge_recordSlice)
	this.ForEach(func(_ int, t *urge_record) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this urge_recordSlice) ToStringMap(indexBy func(t *urge_record) string) (m urge_recordStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(urge_recordStringMap)
	this.ForEach(func(_ int, t *urge_record) {
		m[indexBy(t)] = t
	})
	return m
}
