// Code generated by gsus-db2struct. DO NOT EDIT.
// 催发白名单表
//
//go:generate gsus db2struct urge_whitelist
package table

import "time"

// urge_whitelist : 催发白名单表
type urge_whitelist struct {
	ID            int64     `gorm:"column:id;primary_key;auto_increment;TYPE:bigint;NOT NULL"`                     // 主键ID
	SupplierName  string    `gorm:"column:supplier_name;TYPE:varchar(200);NOT NULL;INDEX:idx_supplier_name"`       // 供应商名称
	SupplierCode  string    `gorm:"column:supplier_code;TYPE:varchar(100);NOT NULL;UNIQUE_INDEX:uk_supplier_code"` // 供应商编码
	ContactName   string    `gorm:"column:contact_name;TYPE:varchar(100);NOT NULL"`                                // 联系人姓名
	ContactPhone  string    `gorm:"column:contact_phone;TYPE:varchar(50);NOT NULL"`                                // 联系电话
	ContactWechat string    `gorm:"column:contact_wechat;TYPE:varchar(100);NOT NULL"`                              // 微信号
	UrgeMethod    string    `gorm:"column:urge_method;TYPE:varchar(50);NOT NULL"`                                  // 催发方式: auto-自动, manual-手动
	UrgeInterval  int       `gorm:"column:urge_interval;TYPE:int;NOT NULL"`                                        // 催发间隔(小时)
	MaxUrgeTimes  int       `gorm:"column:max_urge_times;TYPE:int;NOT NULL"`                                       // 最大催发次数
	Status        int       `gorm:"column:status;TYPE:tinyint;NOT NULL;INDEX:idx_status"`                          // 状态: 1-禁用, 2-启用
	Remark        string    `gorm:"column:remark;TYPE:varchar(500);NOT NULL"`                                      // 备注
	CreatedBy     string    `gorm:"column:created_by;TYPE:varchar(100);NOT NULL"`                                  // 创建人
	UpdatedBy     string    `gorm:"column:updated_by;TYPE:varchar(100);NOT NULL"`                                  // 更新人
	CreatedAt     time.Time `gorm:"column:created_at;TYPE:datetime;NOT NULL"`                                      // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;TYPE:datetime;NOT NULL"`                                      // 更新时间
}

const Tableurge_whitelist = "urge_whitelist"

func (u *urge_whitelist) TableName() string {
	return Tableurge_whitelist
}

type urge_whitelistSlice []urge_whitelist

func (this urge_whitelistSlice) ForEach(f func(index int, t *urge_whitelist)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this urge_whitelistSlice) Filter(f func(t *urge_whitelist) bool) urge_whitelistSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(urge_whitelistSlice, 0, len(this))
	this.ForEach(func(_ int, t *urge_whitelist) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type urge_whitelistIntMap map[int]*urge_whitelist

func (this urge_whitelistIntMap) ForEach(f func(key int, t *urge_whitelist)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this urge_whitelistSlice) MapInt(mapFunc func(*urge_whitelist) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *urge_whitelist) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this urge_whitelistSlice) GroupInt(mapFunc func(*urge_whitelist) int) (ret map[int]urge_whitelistSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]urge_whitelistSlice)
	this.ForEach(func(_ int, t *urge_whitelist) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this urge_whitelistSlice) ToIntMap(indexBy func(t *urge_whitelist) int) (m urge_whitelistIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(urge_whitelistIntMap)
	this.ForEach(func(_ int, t *urge_whitelist) {
		m[indexBy(t)] = t
	})
	return m
}

type urge_whitelistStringMap map[string]*urge_whitelist

func (this urge_whitelistStringMap) ForEach(f func(key string, t *urge_whitelist)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this urge_whitelistSlice) MapString(mapFunc func(*urge_whitelist) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *urge_whitelist) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this urge_whitelistSlice) GroupString(mapFunc func(*urge_whitelist) string) (ret map[string]urge_whitelistSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]urge_whitelistSlice)
	this.ForEach(func(_ int, t *urge_whitelist) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this urge_whitelistSlice) ToStringMap(indexBy func(t *urge_whitelist) string) (m urge_whitelistStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(urge_whitelistStringMap)
	this.ForEach(func(_ int, t *urge_whitelist) {
		m[indexBy(t)] = t
	})
	return m
}
