// Code generated by gsus-db2struct. DO NOT EDIT.
//
//go:generate gsus db2struct orders
package sqlite

import "database/sql"

// Orders struct    订单表.
type Orders struct {
	ID          sql.NullInt64  `gorm:"column:id;primaryKey;type:INTEGER"`
	UserID      int64          `gorm:"column:user_id;type:INTEGER;not null;index:idx_user_id"`
	OrderNo     string         `gorm:"column:order_no;type:TEXT;not null;index:idx_order_no;uniqueIndex:sqlite_autoindex_orders_1"`
	TotalAmount float64        `gorm:"column:total_amount;type:REAL;not null"`
	Status      sql.NullString `gorm:"column:status;type:TEXT;default:'pending'"`
	CreatedAt   sql.NullTime   `gorm:"column:created_at;autoCreateTime;type:DATETIME;default:CURRENT_TIMESTAMP"`
}

const TableOrders = "orders"

func (o *Orders) TableName() string {
	return TableOrders
}

type OrdersSlice []Orders

func (this OrdersSlice) ForEach(f func(index int, t *Orders)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this OrdersSlice) Filter(f func(t *Orders) bool) OrdersSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(OrdersSlice, 0, len(this))
	this.ForEach(func(_ int, t *Orders) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type OrdersIntMap map[int]*Orders

func (this OrdersIntMap) ForEach(f func(key int, t *Orders)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this OrdersSlice) MapInt(mapFunc func(*Orders) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Orders) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this OrdersSlice) GroupInt(mapFunc func(*Orders) int) (ret map[int]OrdersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]OrdersSlice)
	this.ForEach(func(_ int, t *Orders) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this OrdersSlice) ToIntMap(indexBy func(t *Orders) int) (m OrdersIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(OrdersIntMap)
	this.ForEach(func(_ int, t *Orders) {
		m[indexBy(t)] = t
	})
	return m
}

type OrdersStringMap map[string]*Orders

func (this OrdersStringMap) ForEach(f func(key string, t *Orders)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this OrdersSlice) MapString(mapFunc func(*Orders) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Orders) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this OrdersSlice) GroupString(mapFunc func(*Orders) string) (ret map[string]OrdersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]OrdersSlice)
	this.ForEach(func(_ int, t *Orders) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this OrdersSlice) ToStringMap(indexBy func(t *Orders) string) (m OrdersStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(OrdersStringMap)
	this.ForEach(func(_ int, t *Orders) {
		m[indexBy(t)] = t
	})
	return m
}
