// Code generated by gsus-db2struct. DO NOT EDIT.
//
//go:generate gsus db2struct sqlite_sequence
package sqlite

// sqlite_sequence :
type SqliteSequence struct {
	Name interface{} `gorm:"column:name;type:"`
	Seq  interface{} `gorm:"column:seq;type:"`
}

const TableSqliteSequence = "sqlite_sequence"

func (s *SqliteSequence) TableName() string {
	return TableSqliteSequence
}

type SqliteSequenceSlice []SqliteSequence

func (this SqliteSequenceSlice) ForEach(f func(index int, t *SqliteSequence)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this SqliteSequenceSlice) Filter(f func(t *SqliteSequence) bool) SqliteSequenceSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(SqliteSequenceSlice, 0, len(this))
	this.ForEach(func(_ int, t *SqliteSequence) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type SqliteSequenceIntMap map[int]*SqliteSequence

func (this SqliteSequenceIntMap) ForEach(f func(key int, t *SqliteSequence)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this SqliteSequenceSlice) MapInt(mapFunc func(*SqliteSequence) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *SqliteSequence) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this SqliteSequenceSlice) GroupInt(mapFunc func(*SqliteSequence) int) (ret map[int]SqliteSequenceSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]SqliteSequenceSlice)
	this.ForEach(func(_ int, t *SqliteSequence) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this SqliteSequenceSlice) ToIntMap(indexBy func(t *SqliteSequence) int) (m SqliteSequenceIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(SqliteSequenceIntMap)
	this.ForEach(func(_ int, t *SqliteSequence) {
		m[indexBy(t)] = t
	})
	return m
}

type SqliteSequenceStringMap map[string]*SqliteSequence

func (this SqliteSequenceStringMap) ForEach(f func(key string, t *SqliteSequence)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this SqliteSequenceSlice) MapString(mapFunc func(*SqliteSequence) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *SqliteSequence) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this SqliteSequenceSlice) GroupString(mapFunc func(*SqliteSequence) string) (ret map[string]SqliteSequenceSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]SqliteSequenceSlice)
	this.ForEach(func(_ int, t *SqliteSequence) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this SqliteSequenceSlice) ToStringMap(indexBy func(t *SqliteSequence) string) (m SqliteSequenceStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(SqliteSequenceStringMap)
	this.ForEach(func(_ int, t *SqliteSequence) {
		m[indexBy(t)] = t
	})
	return m
}
