package basetmpl

const (
	DefaultImplTemplate = `// Code generated by gsus-impl.
package {{ .ImplPackage }}

import {{ .InterfacePackageName }} "{{ .InterfacePackagePath }}"

var _ {{ .InterfacePackageName }}.{{ .InterfaceName }} = &{{ .ImplStructName }}{}

// @autowire({{ .InterfacePackageName }}.{{ .InterfaceName }},set={{ .SetName }})
type {{ .ImplStructName }} struct {
}
`
)
