// Code generated by gsus-db2struct. DO NOT EDIT.
// 商品表
//
//go:generate gsus db2struct products
package mysql

import "database/sql"

// products : 商品表
type Products struct {
	ID          int64          `gorm:"column:id;PRIMARY_KEY;AUTO_INCREMENT;TYPE:bigint;NOT NULL"`                         // 商品ID
	Name        string         `gorm:"column:name;TYPE:varchar(200);NOT NULL;INDEX:idx_name"`                             // 商品名称
	Description sql.NullString `gorm:"column:description;TYPE:text"`                                                      // 商品描述
	Price       float64        `gorm:"column:price;TYPE:decimal(10,2);NOT NULL"`                                          // 价格
	Stock       sql.NullInt64  `gorm:"column:stock;TYPE:int" sql:"DEFAULT:0"`                                             // 库存
	Category    sql.NullString `gorm:"column:category;TYPE:varchar(50);INDEX:idx_category"`                               // 分类
	Status      sql.NullString `gorm:"column:status;TYPE:enum('active','inactive')" sql:"DEFAULT:active"`                 // 状态
	CreatedAt   sql.NullTime   `gorm:"column:created_at;TYPE:datetime" sql:"DEFAULT:CURRENT_TIMESTAMP DEFAULT_GENERATED"` // 创建时间
}

const TableProducts = "products"

func (p *Products) TableName() string {
	return TableProducts
}

type ProductsSlice []Products

func (this ProductsSlice) ForEach(f func(index int, t *Products)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this ProductsSlice) Filter(f func(t *Products) bool) ProductsSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(ProductsSlice, 0, len(this))
	this.ForEach(func(_ int, t *Products) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type ProductsIntMap map[int]*Products

func (this ProductsIntMap) ForEach(f func(key int, t *Products)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this ProductsSlice) MapInt(mapFunc func(*Products) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Products) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this ProductsSlice) GroupInt(mapFunc func(*Products) int) (ret map[int]ProductsSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]ProductsSlice)
	this.ForEach(func(_ int, t *Products) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this ProductsSlice) ToIntMap(indexBy func(t *Products) int) (m ProductsIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(ProductsIntMap)
	this.ForEach(func(_ int, t *Products) {
		m[indexBy(t)] = t
	})
	return m
}

type ProductsStringMap map[string]*Products

func (this ProductsStringMap) ForEach(f func(key string, t *Products)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this ProductsSlice) MapString(mapFunc func(*Products) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Products) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this ProductsSlice) GroupString(mapFunc func(*Products) string) (ret map[string]ProductsSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]ProductsSlice)
	this.ForEach(func(_ int, t *Products) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this ProductsSlice) ToStringMap(indexBy func(t *Products) string) (m ProductsStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(ProductsStringMap)
	this.ForEach(func(_ int, t *Products) {
		m[indexBy(t)] = t
	})
	return m
}
