// Code generated by gsus-db2struct. DO NOT EDIT.
// 用户表
//
//go:generate gsus db2struct users
package mysql

import "database/sql"

// users : 用户表
type Users struct {
	ID        int64           `gorm:"column:id;primaryKey;autoIncrement;type:bigint;not null"`                                                                      // 用户ID
	Username  string          `gorm:"column:username;type:varchar(50);not null;index:idx_username"`                                                                 // 用户名
	Email     sql.NullString  `gorm:"column:email;type:varchar(100);index:idx_email;uniqueIndex:email"`                                                             // 邮箱
	Password  string          `gorm:"column:password;type:varchar(255);not null"`                                                                                   // 密码
	Age       sql.NullInt64   `gorm:"column:age;type:int"`                                                                                                          // 年龄
	Balance   sql.NullFloat64 `gorm:"column:balance;type:decimal(10,2);default:0.00" sql:"default:0.00"`                                                            // 余额
	IsActive  sql.NullInt64   `gorm:"column:is_active;type:tinyint(1);default:1" sql:"default:1"`                                                                   // 是否激活
	CreatedAt sql.NullTime    `gorm:"column:created_at;autoCreateTime;type:datetime" sql:"default:CURRENT_TIMESTAMP DEFAULT_GENERATED"`                             // 创建时间
	UpdatedAt sql.NullTime    `gorm:"column:updated_at;autoUpdateTime;type:datetime" sql:"default:CURRENT_TIMESTAMP DEFAULT_GENERATED on update CURRENT_TIMESTAMP"` // 更新时间
}

const TableUsers = "users"

func (u *Users) TableName() string {
	return TableUsers
}

type UsersSlice []Users

func (this UsersSlice) ForEach(f func(index int, t *Users)) {
	if len(this) == 0 {
		return
	}
	for i := range this {
		f(i, &this[i])
	}
}

func (this UsersSlice) Filter(f func(t *Users) bool) UsersSlice {
	if len(this) == 0 {
		return nil
	}
	n := make(UsersSlice, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		if f(t) {
			n = append(n, *t)
		}
	})
	return n
}

type UsersIntMap map[int]*Users

func (this UsersIntMap) ForEach(f func(key int, t *Users)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this UsersSlice) MapInt(mapFunc func(*Users) int) (ret []int) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]int, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this UsersSlice) GroupInt(mapFunc func(*Users) int) (ret map[int]UsersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[int]UsersSlice)
	this.ForEach(func(_ int, t *Users) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this UsersSlice) ToIntMap(indexBy func(t *Users) int) (m UsersIntMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(UsersIntMap)
	this.ForEach(func(_ int, t *Users) {
		m[indexBy(t)] = t
	})
	return m
}

type UsersStringMap map[string]*Users

func (this UsersStringMap) ForEach(f func(key string, t *Users)) {
	if len(this) == 0 {
		return
	}
	for k := range this {
		f(k, this[k])
	}
}

func (this UsersSlice) MapString(mapFunc func(*Users) string) (ret []string) {
	if len(this) == 0 {
		return nil
	}
	ret = make([]string, 0, len(this))
	this.ForEach(func(_ int, t *Users) {
		ret = append(ret, mapFunc(t))
	})
	return ret
}

func (this UsersSlice) GroupString(mapFunc func(*Users) string) (ret map[string]UsersSlice) {
	if len(this) == 0 {
		return nil
	}
	ret = make(map[string]UsersSlice)
	this.ForEach(func(_ int, t *Users) {
		ret[mapFunc(t)] = append(ret[mapFunc(t)], *t)
	})
	return ret
}

func (this UsersSlice) ToStringMap(indexBy func(t *Users) string) (m UsersStringMap) {
	if len(this) == 0 {
		return nil
	}
	m = make(UsersStringMap)
	this.ForEach(func(_ int, t *Users) {
		m[indexBy(t)] = t
	})
	return m
}
