package template

const HeadTemplate = `// Code generated by gsus-db2struct. DO NOT EDIT.
// %s
//go:generate gsus db2struct %s
package %s

// %s %s
type %s %s`

const TableFuncTemplate = `const Table%s = "%s"
func (%s *%s) TableName() string {
	return Table%s
}`
