package template

const (
	DefaultHttpClientBaseTemplate string = `// Code generated by gsus-http.
package clients

import (
	"context"
)

type Client struct {
	Host string
}


func NewClient(host string) *Client {
	return &Client{Host:host}
}

func (c Client) DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error) {
	return
}
`

	DefaultHttpClientApiTemplate = `// Code generated by gsus-http. DO NOT EDIT.
package client_{{ .Package }}

import (
	"context"
)


var _ {{ .GroupName }}Client = &Client{}

type Client struct {
	baseClient interface {
		DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error)
	}
}

func NewClient(baseClient interface {
	DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error)
}) {{ .GroupName }}Client {
	return &Client{baseClient: baseClient}
}


type {{ .GroupName }}Client interface {
 	DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error)
	{{ range .ClientApis }}// {{ .Title }}
	{{ .Handler }}{{ .MethodSign }}
	{{ end }}
}

func (c Client) DoRequest(ctx context.Context, method, route string, param, ret interface{}) (err error) {
	return c.baseClient.DoRequest(ctx, method, route, param, ret)
}

{{ range .ClientApis }}// {{ .Title }}
func (c Client) {{ .Handler }}{{ .MethodSign }} {
	err = c.DoRequest(ctx, "{{ .HttpMethod }}", {{ .Route }}, {{ if .Param }}param{{ else }}nil{{ end }},{{ if .Return }}&ret{{ else }}nil{{ end }})
	return
}

{{ end }}
`
)
