package template

const (
	DefaultDaoTemplate = `// Code generated by gsus-template.
package dao

import (
    "context"

    "gorm.io/gorm"
    "{{ .ServicePkgPath }}"
)

// @dao({{ .ModelName }})
type {{ .ModelName }} interface {
    // 获取{{ .ModelDesc }}列表
    Get{{ .ModelName }}List(ctx context.Context, db *gorm.DB, query *{{ .ServicePkg }}.Query{{ .ModelName }}) (list {{ .ServicePkg }}.{{ .ModelName }}List, err error)
    // 通过表单更新{{ .ModelDesc }}
    Update{{ .ModelName }}(ctx context.Context, db *gorm.DB, form *{{ .ServicePkg }}.Form{{ .ModelName }}) (id int,err error)
    // 通过ID删除{{ .ModelDesc }}
    Delete{{ .ModelName }}(ctx context.Context, db *gorm.DB, id int) (err error)
    // 根据ID获取{{ .ModelDesc }}
    Get{{ .ModelName }}ByID(ctx context.Context, db *gorm.DB, id int) (ret {{ .ServicePkg }}.{{ .ModelName }},err error)
}
`

	DefaultDaoImplTemplate = `// Code generated by gsus-template.
package dao_{{ .PackageName }}

import (
    "context"

    "gorm.io/gorm"
    "{{ .ServicePkgPath }}"
)

var _ dao.{{ .ModelName }} = &{{ .StructName }}{}

//@autowire(dao.{{ .ModelName }},set=dao)
type {{ .StructName }} struct {
}


// 获取{{ .ModelDesc }}列表
func ({{ .CallerIdent }} {{ .StructName }}) Get{{ .ModelName }}List(ctx context.Context, db *gorm.DB, query *{{ .ServicePkg }}.Query{{ .ModelName }}) (list {{ .ServicePkg }}.{{ .ModelName }}List, err error) {
    var res {{ .ModelPkg }}.{{ .ModelName }}Slice
    err = db.Find(&res).Error
    if err != nil {
        return
    }
    res.ForEach(func(index int, m *{{ .ModelPkg }}.{{ .ModelName }}) {
        list = append(list, {{ .ServicePkg }}.{{ .ModelName }}{
            Form{{ .ModelName }}: m.ToForm(),
        })
    })
    return
}

// 通过表单更新{{ .ModelDesc }}
func ({{ .CallerIdent }} {{ .StructName }}) Update{{ .ModelName }}(ctx context.Context, db *gorm.DB, form *{{ .ServicePkg }}.Form{{ .ModelName }}) (id int,err error) {
    m := new({{ .ModelPkg }}.{{ .ModelName }}).FromForm(form)
    if err = db.Save(m).Error;err!=nil{
        return
    }
    id = m.ID
    return
}

// 通过ID删除{{ .ModelDesc }}
func ({{ .CallerIdent }} {{ .StructName }}) Delete{{ .ModelName }}(ctx context.Context, db *gorm.DB, id int) (err error) {
    err = db.Delete(&{{ .ModelPkg }}.{{ .ModelName }}{}, "id = ?", id).Error
    return
}

// 根据ID获取{{ .ModelDesc }}
func ({{ .CallerIdent }} {{ .StructName }}) Get{{ .ModelName }}ByID(ctx context.Context, db *gorm.DB, id int) (ret {{ .ServicePkg }}.{{ .ModelName }},err error) {
    m := new({{ .ModelPkg }}.{{ .ModelName }})
    err = db.Where("id = ?",id).Find(&m).Error
    if err!=nil{
        return
    }
    ret = {{ .ServicePkg }}.{{ .ModelName }}{
        Form{{ .ModelName }}: m.ToForm(),
    }
    return
}`

	DefaultModelCastTemplate = `// Code generated by gsus-template. DO NOT EDIT.
package {{ .ModelPkg }}

import (
	"{{ .ServicePkgPath }}"
)

func (this *{{ .ModelName }}) ToForm() {{ .ServicePkg }}.Form{{ .ModelName }} {
	return {{ .ServicePkg }}.Form{{ .ModelName }}{ {{ range $Field := .Fields}}
			{{ $Field.Name }} : this.{{ $Field.Name }},{{ end }}
	}
}

func (this *{{ .ModelName }}) FromForm(form *{{ .ServicePkg }}.Form{{ .ModelName }}) *{{ .ModelName }}{
	*this = {{ .ModelName }}{ {{ range $Field := .Fields}}
		{{ $Field.Name }} : form.{{ $Field.Name }},{{ end }}
	}
	return this
}
`

	DefaultServiceTemplate = `// Code generated by gsus-template.
package service

import (
    "context"
)

// {{ .ModelDesc }}服务接口定义
// @service({{ .PackageName }})
type {{ .ModelName }}Service interface {
    // 获取{{ .ModelDesc }}列表
    // @http.get("/list")
    Get{{ .ModelName }}List(ctx context.Context, param Query{{ .ModelName }}) (list {{ .ModelName }}List, err error)
    // 编辑{{ .ModelDesc }}
    // @http.post("")
    Update{{ .ModelName }}(ctx context.Context, param Form{{ .ModelName }}) (err error)
    // 删除{{ .ModelDesc }}
    // @http.delete("")
    Delete{{ .ModelName }}(ctx context.Context, param Query{{ .ModelName }}) (err error)
    // 根据ID获取{{ .ModelDesc }}
    Get{{ .ModelName }}ByID(ctx context.Context, id int) (ret {{ .ModelName }}, err error)
}

// {{ .ModelDesc }}表单定义
type Form{{ .ModelName }} struct { {{ range $Field := .Fields}}
        {{ $Field.Name }} {{ $Field.Type }} // {{ $Field.Comment}}   {{ end }}
}

// {{ .ModelDesc }}查询定义
type Query{{ .ModelName }} struct {
    ID int
}

// {{ .ModelDesc }}列表定义
type {{ .ModelName }} struct {
    Form{{ .ModelName }}
}

type {{ .ModelName }}List []{{ .ModelName }}

func (l {{ .ModelName }}List) ViewItem() interface{} {
    return new({{ .ModelName }})
}`

	DefaultServiceImplTemplate = `// Code generated by gsus-template.
package svc_{{ .PackageName }}

import (
    "context"

    "{{ .ServicePkgPath }}"
)

var _ {{ .ServicePkg }}.{{ .ModelName }}Service = &{{ .StructName }}{}

// {{ .ModelDesc }}服务
// @autowire({{ .ServicePkg }}.{{ .ModelName }}Service,set=service)
type {{ .StructName }} struct {
    SQL isql.GormSQL
    Dao{{ .ModelName }} dao.{{ .ModelName }}
}

// 编辑{{ .ModelDesc }}
func ({{ .CallerIdent }}  {{ .StructName }}) Update{{ .ModelName }}(ctx context.Context, param {{ .ServicePkg }}.Form{{ .ModelName }}) (err error) {
    db:= {{ .CallerIdent }}.SQL.GetDB(ctx)
    _,err = {{ .CallerIdent }}.Dao{{ .ModelName }}.Update{{ .ModelName }}(ctx, db, &param)
    return
}

// 获取{{ .ModelDesc }}列表
func ({{ .CallerIdent }} {{ .StructName }}) Get{{ .ModelName }}List(ctx context.Context, param {{ .ServicePkg }}.Query{{ .ModelName }}) (list {{ .ServicePkg }}.{{ .ModelName }}List, err error) {
    db:= {{ .CallerIdent }}.SQL.GetDB(ctx)
    list, err = {{ .CallerIdent }}.Dao{{ .ModelName }}.Get{{ .ModelName }}List(ctx, db, &param)
    return
}

// 根据ID获取{{ .ModelDesc }}
func ({{ .CallerIdent }} {{ .StructName }}) Get{{ .ModelName }}ByID(ctx context.Context, id int) (ret {{ .ServicePkg }}.{{ .ModelName }}, err error) {
    db:= {{ .CallerIdent }}.SQL.GetDB(ctx)
    ret, err = {{ .CallerIdent }}.Dao{{ .ModelName }}.Get{{ .ModelName }}ByID(ctx, db, id)
    return
}

// 删除{{ .ModelDesc }}
func ({{ .CallerIdent }} {{ .StructName }}) Delete{{ .ModelName }}(ctx context.Context, param {{ .ServicePkg }}.Query{{ .ModelName }}) (err error) {
    db:= {{ .CallerIdent }}.SQL.GetDB(ctx)
    err = {{ .CallerIdent }}.Dao{{ .ModelName }}.Delete{{ .ModelName }}(ctx, db, param.ID)
    return
}
`
)
